In [5]:
!pip install opencv-python

import numpy as np
import pandas as pd
import cv2
import os

DEPRECATION: Configuring installation scheme with distutils config files is deprecated and will no longer work in the near future. If you are using a Homebrew or Linuxbrew Python, please see discussion at https://github.com/Homebrew/homebrew-core/issues/76621
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 32.6/32.6 MB 31.5 MB/s eta 0:00:00m eta 0:00:010:00:01
  DEPRECATION: Configuring installation scheme with distutils config files is deprecated and will no longer work in the near future. If you are using a Homebrew or Linuxbrew Python, please see discussion at https://github.com/Homebrew/homebrew-core/issues/76621
DEPRECATION: Configuring installation scheme with distutils config files is deprecated and will no longer work in the near future. If you are using a Homebrew or Linuxbrew Python, please see discussion at https://github.com/Homebrew/homebrew-core/issues/76621


In [9]:
# 루트 디렉토리
root_dir = '/Users/jang-youngjoon/dev-projects/youtuber-look-alike/dummy-img'

In [19]:
# 송혜교
selected_celeb = 'shg'
path = os.path.join(root_dir, selected_celeb)
file_list = os.listdir(path)

In [20]:
len(file_list)

401

In [21]:
file_list.sort()

In [22]:
file_list

['.DS_Store',
 'image_shg_1.jpg',
 'image_shg_10.jpg',
 'image_shg_100.jpg',
 'image_shg_101.jpg',
 'image_shg_102.jpg',
 'image_shg_103.jpg',
 'image_shg_104.jpg',
 'image_shg_105.jpg',
 'image_shg_106.jpg',
 'image_shg_107.jpg',
 'image_shg_108.jpg',
 'image_shg_109.jpg',
 'image_shg_11.jpg',
 'image_shg_110.jpg',
 'image_shg_111.jpg',
 'image_shg_112.jpg',
 'image_shg_113.jpg',
 'image_shg_114.jpg',
 'image_shg_115.jpg',
 'image_shg_116.jpg',
 'image_shg_117.jpg',
 'image_shg_118.jpg',
 'image_shg_119.jpg',
 'image_shg_12.jpg',
 'image_shg_120.jpg',
 'image_shg_121.jpg',
 'image_shg_122.jpg',
 'image_shg_123.jpg',
 'image_shg_124.jpg',
 'image_shg_125.jpg',
 'image_shg_126.jpg',
 'image_shg_127.jpg',
 'image_shg_128.jpg',
 'image_shg_129.jpg',
 'image_shg_13.jpg',
 'image_shg_130.jpg',
 'image_shg_131.jpg',
 'image_shg_132.jpg',
 'image_shg_133.jpg',
 'image_shg_134.jpg',
 'image_shg_135.jpg',
 'image_shg_136.jpg',
 'image_shg_137.jpg',
 'image_shg_138.jpg',
 'image_shg_139.jpg',
 '

In [26]:
for file in file_list:
    image_path = os.path.join(path, file)
    image = cv2.imread(image_path)
    print(image)

None
[[[ 26  21  20]
  [ 26  21  20]
  [ 25  20  19]
  ...
  [236 222 234]
  [236 222 234]
  [236 222 234]]

 [[ 26  21  20]
  [ 26  21  20]
  [ 25  20  19]
  ...
  [255 241 253]
  [255 241 253]
  [255 241 253]]

 [[ 26  21  20]
  [ 26  21  20]
  [ 25  20  19]
  ...
  [254 240 252]
  [253 239 251]
  [253 239 251]]

 ...

 [[157 164 149]
  [157 164 149]
  [156 163 148]
  ...
  [169 180 212]
  [170 180 214]
  [171 182 214]]

 [[154 161 146]
  [157 164 149]
  [158 165 150]
  ...
  [171 182 214]
  [173 182 215]
  [174 185 217]]

 [[156 163 150]
  [158 165 152]
  [157 164 151]
  ...
  [169 179 209]
  [175 183 213]
  [171 181 211]]]
[[[209 210 206]
  [209 210 206]
  [209 210 206]
  ...
  [243 242 238]
  [243 242 238]
  [243 242 238]]

 [[209 210 206]
  [209 210 206]
  [209 210 206]
  ...
  [243 242 238]
  [243 242 238]
  [243 242 238]]

 [[209 210 206]
  [209 210 206]
  [209 210 206]
  ...
  [243 242 238]
  [243 242 238]
  [243 242 238]]

 ...

 [[207 208 204]
  [207 208 204]
  [207 208 204]

[[[157 157 157]
  [158 158 158]
  [159 159 159]
  ...
  [240 240 240]
  [240 240 240]
  [240 240 240]]

 [[155 155 155]
  [156 156 156]
  [157 157 157]
  ...
  [240 240 240]
  [240 240 240]
  [240 240 240]]

 [[154 154 154]
  [154 154 154]
  [155 155 155]
  ...
  [240 240 240]
  [240 240 240]
  [240 240 240]]

 ...

 [[158 158 158]
  [158 158 158]
  [159 159 159]
  ...
  [171 171 171]
  [171 171 171]
  [170 170 170]]

 [[159 159 159]
  [159 159 159]
  [160 160 160]
  ...
  [171 171 171]
  [171 171 171]
  [170 170 170]]

 [[157 157 157]
  [158 158 158]
  [158 158 158]
  ...
  [171 171 171]
  [171 171 171]
  [170 170 170]]]
[[[ 45  39  40]
  [ 45  39  40]
  [ 45  39  40]
  ...
  [ 31 138 175]
  [ 38 146 180]
  [ 60 168 202]]

 [[ 45  39  40]
  [ 45  39  40]
  [ 45  39  40]
  ...
  [ 30 137 174]
  [ 37 145 179]
  [ 59 167 201]]

 [[ 45  39  40]
  [ 45  39  40]
  [ 45  39  40]
  ...
  [ 29 136 173]
  [ 37 145 179]
  [ 59 167 201]]

 ...

 [[ 82 109 176]
  [ 83 110 177]
  [ 84 111 178]
  ..