In [5]:
!pip install opencv-python

import numpy as np
import pandas as pd
import cv2
import os

DEPRECATION: Configuring installation scheme with distutils config files is deprecated and will no longer work in the near future. If you are using a Homebrew or Linuxbrew Python, please see discussion at https://github.com/Homebrew/homebrew-core/issues/76621
DEPRECATION: Configuring installation scheme with distutils config files is deprecated and will no longer work in the near future. If you are using a Homebrew or Linuxbrew Python, please see discussion at https://github.com/Homebrew/homebrew-core/issues/76621


### Load images

In [2]:
# 전체 이미지 가져오는 루트 디렉토리
root_dir = '/Users/jang-youngjoon/dev-projects/youtuber-look-alike/crawled-image'

In [3]:
# 송혜교
selected_celeb = 'idh'
path = os.path.join(root_dir, selected_celeb)
file_list = os.listdir(path)

In [4]:
file_list

['image_idh_203.jpg',
 'image_idh_38.jpg',
 'image_idh_217.jpg',
 'image_idh_10.jpg',
 'image_idh_175.jpg',
 'image_idh_161.jpg',
 'image_idh_149.jpg',
 'image_idh_388.jpg',
 'image_idh_377.jpg',
 'image_idh_363.jpg',
 'image_idh_362.jpg',
 'image_idh_376.jpg',
 'image_idh_389.jpg',
 'image_idh_148.jpg',
 'image_idh_160.jpg',
 'image_idh_174.jpg',
 'image_idh_11.jpg',
 'image_idh_216.jpg',
 'image_idh_202.jpg',
 'image_idh_39.jpg',
 'image_idh_214.jpg',
 'image_idh_200.jpg',
 'image_idh_228.jpg',
 'image_idh_13.jpg',
 'image_idh_189.jpg',
 'image_idh_162.jpg',
 'image_idh_176.jpg',
 'image_idh_360.jpg',
 'image_idh_374.jpg',
 'image_idh_348.jpg',
 'image_idh_349.jpg',
 'image_idh_375.jpg',
 'image_idh_361.jpg',
 'image_idh_177.jpg',
 'image_idh_163.jpg',
 'image_idh_188.jpg',
 'image_idh_229.jpg',
 'image_idh_12.jpg',
 'image_idh_201.jpg',
 'image_idh_215.jpg',
 'image_idh_16.jpg',
 'image_idh_239.jpg',
 'image_idh_211.jpg',
 'image_idh_205.jpg',
 'image_idh_198.jpg',
 'image_idh_167.j

### Read image using cv2

In [5]:
for file in file_list:
    image_path = os.path.join(path, file)
    image = cv2.imread(image_path)
    print(image)

[[[248 234 222]
  [248 234 222]
  [248 234 222]
  ...
  [208 198 210]
  [208 198 210]
  [202 192 204]]

 [[248 234 222]
  [248 234 222]
  [248 234 222]
  ...
  [208 198 210]
  [208 198 210]
  [212 202 214]]

 [[248 234 222]
  [248 234 222]
  [248 234 222]
  ...
  [208 198 210]
  [208 198 210]
  [215 205 217]]

 ...

 [[ 54  30  24]
  [ 57  33  27]
  [ 59  37  31]
  ...
  [ 43  22  24]
  [ 40  22  23]
  [ 40  22  23]]

 [[ 54  30  24]
  [ 57  33  27]
  [ 59  37  31]
  ...
  [ 43  22  24]
  [ 42  21  23]
  [ 42  21  23]]

 [[ 54  30  24]
  [ 57  33  27]
  [ 59  37  31]
  ...
  [ 44  22  24]
  [ 42  21  23]
  [ 42  21  23]]]
[[[ 16  15  25]
  [ 19  18  28]
  [ 22  21  31]
  ...
  [214 213 223]
  [213 212 222]
  [213 212 222]]

 [[ 17  16  26]
  [ 19  18  28]
  [ 22  21  31]
  ...
  [214 213 223]
  [213 212 222]
  [213 212 222]]

 [[ 18  17  27]
  [ 20  19  29]
  [ 22  21  31]
  ...
  [214 213 223]
  [213 212 222]
  [213 212 222]]

 ...

 [[208 207 217]
  [205 204 214]
  [201 200 210]
  ..

[[[165 165 151]
  [175 176 160]
  [182 182 166]
  ...
  [252 255 253]
  [252 255 253]
  [250 255 253]]

 [[194 193 179]
  [204 203 189]
  [212 209 194]
  ...
  [254 255 253]
  [252 255 253]
  [250 255 253]]

 [[227 221 210]
  [237 231 218]
  [244 236 223]
  ...
  [254 255 253]
  [252 255 253]
  [252 255 253]]

 ...

 [[239 239 239]
  [239 239 239]
  [239 239 239]
  ...
  [239 239 239]
  [239 239 239]
  [239 239 239]]

 [[239 239 239]
  [239 239 239]
  [239 239 239]
  ...
  [239 239 239]
  [239 239 239]
  [239 239 239]]

 [[239 239 239]
  [239 239 239]
  [239 239 239]
  ...
  [239 239 239]
  [239 239 239]
  [239 239 239]]]
[[[ 79 175 211]
  [ 79 175 211]
  [ 80 176 212]
  ...
  [ 72 164 199]
  [ 72 164 199]
  [ 71 163 198]]

 [[ 79 175 211]
  [ 80 176 212]
  [ 80 176 212]
  ...
  [ 72 164 199]
  [ 72 164 199]
  [ 72 164 199]]

 [[ 80 176 212]
  [ 80 176 212]
  [ 80 176 212]
  ...
  [ 75 165 200]
  [ 74 164 199]
  [ 74 164 199]]

 ...

 [[ 79 174 217]
  [ 80 175 218]
  [ 80 175 218]
  ..

### Test

In [6]:
sample_image_path = '/Users/jang-youngjoon/dev-projects/youtuber-look-alike/crawled-image/shg/image_shg_1.jpg'

In [7]:
sample_image = cv2.imread(sample_image_path)

In [8]:
sample_image

array([[[ 26,  21,  20],
        [ 26,  21,  20],
        [ 25,  20,  19],
        ...,
        [236, 222, 234],
        [236, 222, 234],
        [236, 222, 234]],

       [[ 26,  21,  20],
        [ 26,  21,  20],
        [ 25,  20,  19],
        ...,
        [255, 241, 253],
        [255, 241, 253],
        [255, 241, 253]],

       [[ 26,  21,  20],
        [ 26,  21,  20],
        [ 25,  20,  19],
        ...,
        [254, 240, 252],
        [253, 239, 251],
        [253, 239, 251]],

       ...,

       [[157, 164, 149],
        [157, 164, 149],
        [156, 163, 148],
        ...,
        [169, 180, 212],
        [170, 180, 214],
        [171, 182, 214]],

       [[154, 161, 146],
        [157, 164, 149],
        [158, 165, 150],
        ...,
        [171, 182, 214],
        [173, 182, 215],
        [174, 185, 217]],

       [[156, 163, 150],
        [158, 165, 152],
        [157, 164, 151],
        ...,
        [169, 179, 209],
        [175, 183, 213],
        [171, 181, 211]]

In [9]:
face_cascade = cv2.CascadeClassifier("haarcascade_frontalface_default.xml")

In [10]:
gray = cv2.cvtColor(sample_image, cv2.COLOR_BGR2GRAY)

In [11]:
gray

array([[ 21,  21,  20, ..., 227, 227, 227],
       [ 21,  21,  20, ..., 246, 246, 246],
       [ 21,  21,  20, ..., 245, 244, 244],
       ...,
       [159, 159, 158, ..., 188, 189, 190],
       [156, 159, 160, ..., 190, 191, 193],
       [158, 160, 159, ..., 187, 191, 189]], dtype=uint8)

In [12]:
faces = face_cascade.detectMultiScale(gray, 1.3, 5)

In [13]:
for (x, y, w, h) in faces:
    cv2.rectangle(sample_image, (x, y), (x + w, y + h), (255,0,0), 2)
    cropped_image = image[y : y+h, x : x+w]
    resized_image = cv2.resize(cropped_image, (180, 180))
#     cv2.imshow("crop & resize", resized_image)
#     cv2.waitKey(0)
    

# Make crop_face function and save file

In [1]:
# 원본 파일 가져올 root 디렉토리
import_root_path = '/Users/jang-youngjoon/dev-projects/youtuber-look-alike/crawled-image'

# 전처리된 파일 저장할 root 디렉토리
save_root_path = '/Users/jang-youngjoon/dev-projects/youtuber-look-alike/pre-processed-image'

In [2]:
celeb_name = input('가져올 연예인의 이름을 입력하세요: ')
celeb_name_to_en = ''

가져올 연예인의 이름을 입력하세요: 임지연


In [3]:
if celeb_name == '송혜교':
    celeb_name_to_en = 'shg'
elif celeb_name == '이도현': 
      celeb_name_to_en = 'idh'
elif celeb_name == '임지연':
      celeb_name_to_en = 'ijh'
elif celeb_name == '신예은':
      celeb_name_to_en = 'she'

#### Import files

In [6]:
import_path = os.path.join(import_root_path, celeb_name_to_en)
image_list = os.listdir(import_path)

save_path = str(os.path.join(save_root_path, celeb_name_to_en))

In [7]:
def crop_face(image, name):
    # face_cascade 모델 사용
    face_cascade = cv2.CascadeClassifier("haarcascade_frontalface_default.xml")
    gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
    faces = face_cascade.detectMultiScale(gray, 1.3, 5)

    for (x, y, w, h) in faces:
        cropped_image = image[y : y+h, x : x+w]
        resized_image = cv2.resize(cropped_image, (180, 180))
        cv2.imwrite(os.path.join(save_path, name), resized_image)
        print(f"{celeb_name_to_en} image cropped & saved" )

In [8]:
for image_name in image_list:
    # .DS Store 파일 확인
    if 'jpg' in image_name:
        original_image = cv2.imread(os.path.join(import_path, str(image_name)))
        # 백색 이미지 방지 할라했는데 안됨,,,
        if (type(original_image) != 'NoneType' or original_image != None) :
            crop_face(original_image, image_name)   
        else:
            continue
    else:
        continue

ijh image cropped & saved
ijh image cropped & saved
ijh image cropped & saved
ijh image cropped & saved
ijh image cropped & saved
ijh image cropped & saved
ijh image cropped & saved
ijh image cropped & saved
ijh image cropped & saved
ijh image cropped & saved
ijh image cropped & saved
ijh image cropped & saved
ijh image cropped & saved
ijh image cropped & saved
ijh image cropped & saved
ijh image cropped & saved
ijh image cropped & saved
ijh image cropped & saved
ijh image cropped & saved
ijh image cropped & saved
ijh image cropped & saved
ijh image cropped & saved
ijh image cropped & saved
ijh image cropped & saved
ijh image cropped & saved
ijh image cropped & saved
ijh image cropped & saved
ijh image cropped & saved
ijh image cropped & saved
ijh image cropped & saved
ijh image cropped & saved
ijh image cropped & saved
ijh image cropped & saved
ijh image cropped & saved
ijh image cropped & saved
ijh image cropped & saved
ijh image cropped & saved
ijh image cropped & saved
ijh image cr

ijh image cropped & saved
ijh image cropped & saved
ijh image cropped & saved
ijh image cropped & saved
ijh image cropped & saved
ijh image cropped & saved
ijh image cropped & saved
ijh image cropped & saved
ijh image cropped & saved
ijh image cropped & saved
ijh image cropped & saved
ijh image cropped & saved
ijh image cropped & saved
ijh image cropped & saved
ijh image cropped & saved
ijh image cropped & saved
ijh image cropped & saved
ijh image cropped & saved
ijh image cropped & saved
ijh image cropped & saved
ijh image cropped & saved
ijh image cropped & saved
ijh image cropped & saved
ijh image cropped & saved
ijh image cropped & saved
ijh image cropped & saved
ijh image cropped & saved
ijh image cropped & saved
ijh image cropped & saved
ijh image cropped & saved
ijh image cropped & saved
ijh image cropped & saved
ijh image cropped & saved
ijh image cropped & saved
ijh image cropped & saved
ijh image cropped & saved
ijh image cropped & saved
ijh image cropped & saved
ijh image cr