In [8]:
!pip install -U albumentations
!pip install torch torchvision
!pip install matplotlib

DEPRECATION: Configuring installation scheme with distutils config files is deprecated and will no longer work in the near future. If you are using a Homebrew or Linuxbrew Python, please see discussion at https://github.com/Homebrew/homebrew-core/issues/76621
DEPRECATION: Configuring installation scheme with distutils config files is deprecated and will no longer work in the near future. If you are using a Homebrew or Linuxbrew Python, please see discussion at https://github.com/Homebrew/homebrew-core/issues/76621
DEPRECATION: Configuring installation scheme with distutils config files is deprecated and will no longer work in the near future. If you are using a Homebrew or Linuxbrew Python, please see discussion at https://github.com/Homebrew/homebrew-core/issues/76621
DEPRECATION: Configuring installation scheme with distutils config files is deprecated and will no longer work in the near future. If you are using a Homebrew or Linuxbrew Python, please see discussion at https://github.

  DEPRECATION: Configuring installation scheme with distutils config files is deprecated and will no longer work in the near future. If you are using a Homebrew or Linuxbrew Python, please see discussion at https://github.com/Homebrew/homebrew-core/issues/76621
  DEPRECATION: Configuring installation scheme with distutils config files is deprecated and will no longer work in the near future. If you are using a Homebrew or Linuxbrew Python, please see discussion at https://github.com/Homebrew/homebrew-core/issues/76621
  DEPRECATION: Configuring installation scheme with distutils config files is deprecated and will no longer work in the near future. If you are using a Homebrew or Linuxbrew Python, please see discussion at https://github.com/Homebrew/homebrew-core/issues/76621
  DEPRECATION: Configuring installation scheme with distutils config files is deprecated and will no longer work in the near future. If you are using a Homebrew or Linuxbrew Python, please see discussion at https:/

In [23]:
from torch.utils.data import Dataset
from torchvision import transforms
from PIL import Image
from matplotlib import pyplot as plt
import albumentations
from albumentations.pytorch import ToTensorV2
import torch
import torchvision
import os
import cv2

In [24]:
root_path = '/Users/jang-youngjoon/dev-projects/youtuber-look-alike/pre-processed-image'
image_initial_list = ['shg', 'idh', 'ijh', 'she']

In [25]:
class AlbumentationsDataset(Dataset):
    def __init__(self, file_path, labels, transform=None):
        self.file_path = file_path
        self.labels = labels
        self.transform = transform

# 파일 여러개 처리할 수 있도록 수정 필요
    def __getitem__(self, index):
        label = self.labels[index]
        file_path = self.file_path[index]

        image = cv2.imread(file_path)

        image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)

        start_t = time.time()
        if self.transform:
            augmented = self.transform(image=image)
            image = augmented['image']

        total_time = (time.time() - start_t)

        return image, label, total_time

    def __len__(self):
        return len(self.file_path)

In [27]:
albumentations_transform = albumentations.Compose([
    albumentations.HorizontalFlip(p=0.5),
    albumentations.RandomBrightnessContrast(p=0.5),
    albumentations.RandomBrightnessContrast(brightness_limit=(-0.3, 0.3), contrast_limit=(-0.3, 0.3), p=1),
    albumentations.ChannelShuffle(p=0.2),
    ToTensorV2()
])

In [21]:
for image_initial in image_initial_list:
    image_list_path = os.path.join(root_path, image_initial)
    image_list = os.listdir(image_list_path)
    for image in image_list:
        image_path = os.path.join(image_list_path, image)
        image = cv2.imread(image_path)
        print(image)

[[[ 31  25  26]
  [ 31  25  26]
  [ 31  25  26]
  ...
  [166 142 106]
  [166 141 107]
  [166 141 107]]

 [[ 31  25  26]
  [ 31  25  26]
  [ 31  25  26]
  ...
  [166 142 106]
  [165 140 106]
  [165 140 106]]

 [[ 31  25  26]
  [ 31  25  26]
  [ 31  25  26]
  ...
  [165 141 105]
  [164 139 105]
  [164 139 105]]

 ...

 [[ 25  20  21]
  [ 25  20  21]
  [ 25  20  21]
  ...
  [ 59  51  58]
  [ 58  47  55]
  [ 58  47  55]]

 [[ 25  20  21]
  [ 25  20  21]
  [ 25  20  21]
  ...
  [ 59  51  58]
  [ 58  47  55]
  [ 57  46  54]]

 [[ 25  20  21]
  [ 25  20  21]
  [ 25  20  21]
  ...
  [ 59  51  58]
  [ 58  47  55]
  [ 57  46  54]]]
[[[ 39  29  29]
  [ 39  29  29]
  [ 39  29  29]
  ...
  [175 145 116]
  [175 145 116]
  [175 145 116]]

 [[ 39  29  29]
  [ 39  29  29]
  [ 39  29  29]
  ...
  [174 144 115]
  [175 145 116]
  [175 145 116]]

 [[ 38  28  28]
  [ 38  28  28]
  [ 38  28  28]
  ...
  [172 144 114]
  [173 143 114]
  [173 143 114]]

 ...

 [[ 38  31  44]
  [ 38  31  44]
  [ 38  31  44]
  ..