In [1]:
pip install opencv-python

Note: you may need to restart the kernel to use updated packages.


In [2]:
pip install Pillow

Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np
import cv2
import os
import pandas as pd

In [4]:
path = 'C:/Users/82103/Documents/Deep daiv/deep_learning_wiki/youtuber_alike/'

### png to jpg

In [5]:
from PIL import Image
path = 'C:/Users/82103/Documents/Deep daiv/deep_learning_wiki/youtuber_alike/ojy/'
file_list = os.listdir(path)
for i in range(len(file_list)):
    if file_list[i][-4:] == 'jpeg':
        Image.open(path + '/'+file_list[i]).convert('RGB').save(path + '/' + file_list[i][:-4] +'.jpg')
        os.remove(path + '/'+file_list[i])

### 이미지 한 개로 얼굴 크롭 코드 연습

In [5]:
import cv2

face_cascade = cv2.CascadeClassifier("C:\\Users\\82103\\Documents\\Deep daiv\\deep_learning_wiki\\youtuber_alike\\haar-cascade-files\\haarcascade_frontalface_alt.xml")
eye_cascade = cv2.CascadeClassifier('C:\\Users\\82103\\Documents\\Deep daiv\\deep_learning_wiki\\youtuber_alike\\haar-cascade-files\\haarcascade_eye.xml')

In [6]:
img = cv2.imread('C:/Users/82103/Documents/Deep daiv/deep_learning_wiki/youtuber_alike/ojy/000001.jpg')
print(img)

[[[240 232 225]
  [240 232 225]
  [241 233 226]
  ...
  [202 203 201]
  [198 199 197]
  [196 197 195]]

 [[240 232 225]
  [240 232 225]
  [240 232 225]
  ...
  [205 203 202]
  [201 199 198]
  [199 197 196]]

 [[239 231 224]
  [239 231 224]
  [240 232 225]
  ...
  [206 204 203]
  [202 200 199]
  [200 198 197]]

 ...

 [[242 242 242]
  [242 242 242]
  [243 243 243]
  ...
  [242 242 242]
  [242 242 242]
  [242 242 242]]

 [[242 242 242]
  [242 242 242]
  [242 242 242]
  ...
  [242 242 242]
  [242 242 242]
  [242 242 242]]

 [[242 242 242]
  [242 242 242]
  [242 242 242]
  ...
  [242 242 242]
  [242 242 242]
  [242 242 242]]]


In [7]:
gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
faces = face_cascade.detectMultiScale(gray, 1.3,5)

In [1]:
# ?? 
for (x,y,w,h) in faces:
    cv2.rectangle(img,(x,y),(x+w,y+h),(0,255,0),2)
    cropped = img[y: y+h, x:x+w]
    resize = cv2.resize(cropped, (180,180))
    cv2.imshow("crop&resize", resize)
    cv2.waitKey(0)
    cv2.destroyAllWindows()

NameError: name 'faces' is not defined

In [31]:
for (x,y,w,h) in faces:
    # cv2.rectangle(img,(x,y),(x+w,y+h),(0,255,0),2)
    cropped = img[y: y+h, x:x+w]
    resize = cv2.resize(cropped, (180,180))
    cv2.imwrite('C:/Users/82103/Documents/Deep daiv/deep_learning_wiki/youtuber_alike/ojy/000001.jpg', resize)

### 얼굴 크롭하는 함수 만들기

In [8]:
def cropping_face(image, name, path):
    face_cascade = cv2.CascadeClassifier("C:\\Users\\82103\\Documents\\Deep daiv\\deep_learning_wiki\\youtuber_alike\\haar-cascade-files\\haarcascade_frontalface_alt2.xml")
    gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
    faces = face_cascade.detectMultiScale(gray, 1.3, 5)
    for (x,y,w,h) in faces:
        #cv2.rectangle(image,(x,y),(x+w,y+h),(0,255,0),2)
        cropped = image[y: y+h, x:x+w]
        resize = cv2.resize(cropped, (180,180))
        #cv2.imshow("crop&resize", resize)
        #cv2.waitKey(0)
        #cv2.destroyAllWindows()
        
        cv2.imwrite(path + file_list[i], resize)

In [ ]:
for name in file_name_list:
    img = cv2.imread('C:/Users/mnju5/2023-youtuber-crawling/youtuber-look-alike-crawler/mo/'+name)
    cropping_face(img, name)

In [16]:
name_list = ['ojy', 'jjj', 'jsi', 'khar']
for name in name_list:
    path = 'C:/Users/82103/Documents/Deep daiv/deep_learning_wiki/youtuber_alike/'+ name + '/'
    file_list = os.listdir(path)
    print(file_list[0])
    for i in range(len(file_list)):
        img = cv2.imread(path + file_list[i])
        cropping_face(img, name, path)

000001.jpg
000001.jpg
000001.jpg
000001.jpg


In [12]:
path = 'C:/Users/82103/Documents/Deep daiv/deep_learning_wiki/youtuber_alike/ojy/'
file_list = os.listdir(path)
print(file_list[0])
for i in range(len(file_list)):
    img = cv2.imread(path + file_list[i])
    cropping_face(img, 'ojy', path)

000001.jpg
